name: Lint, Test and Deploy Single Job
on: workflow_dispatch
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Get code
              uses: actions/checkout@v4
            - name: Install NodeJS
              uses: actions/setup-node@v4
              with:
                node-version: 18
            - name: Install dependencies
              run: npm ci
            - name: Run linter
              run: npm run lint
            - name: Test app
              run: npm test
            - name: Build App
              run: npm run build
            - name: Deploy
              run: echo "Deploying..."